### ISSUE TITLE
USB-USB: suspend/wake support for keyboard

### ISSUE THREAD

**Issue by tmk** [tmk/tmk_keyboard#769]
# Problem
The converter does not support to suspend a keyboard. MAX3421E and keyboard keep drawing power while computer is sleeping.

## TODO

- [x] Add suspend and wake support to USB_Host_Shield_2.0
- [x] Add retmote wakeup support to USB_Host_Shield_2.0
- [x] Converter suspends a keyboard while sleeping
- [x] MAX3421E power saving

**Comment by tmk** [comment]
# MAX3421e RWUIRQ issue

Seemingly `RWUIRQ` is not triggered with remote wakeup from some devices. This seems to depend on remote wake implementation and singnal term(1-15ms).

RWUIRQ does not work with:
- TMK Alps64(LUFA) - full speed
- HHKB Classic - full speed
- Realforce RGB - full speed

OK with:
- VARMILO MA109C - full speed
- Cherry G80-3600 - low speed
- ThinkPad keyboard
- Poker X - low speed

https://electronics.stackexchange.com/questions/372236/bugs-in-maxim-chip-max3421e-used-as-usb-host


## WORK AROUND
Check bus state using `SAMPLEBUS` and detect remote wakeup signal when bus is K state.

```
        // sample bus
        regWr(rHCTL, bmSAMPLEBUS);
        while(!(regRd(rHCTL) & bmSAMPLEBUS));

        uint8_t bus_sample;
        bus_sample = regRd(rHRSL);
        bus_sample &= (bmJSTATUS | bmKSTATUS);
                  
        // if K-sate    
        if (bus_sample == bmKSTATUS) {
            // remote wakeup
        }
```

**Comment by tmk** [comment]
# DEVICE_REMOTE_WAKEUP


To enable Remote Wakeup on a device/keyboard
we need to send `SET_FEATURE` request using `ctrlReq()` :

```
        // SET_FEATURE(DEVICE_REMOTE_WAKEUP)                    
        rcode = pUsb->ctrlReq(bAddress,                        
                        0, // End Point: 0                                                                            
                        (USB_SETUP_HOST_TO_DEVICE | USB_SETUP_TYPE_STANDARD | USB_SETUP_RECIPIENT_DEVICE), // bmRequestType                                                                                                                 
                        USB_REQUEST_SET_FEATURE,    // bRequest                             
                        USB_FEATURE_DEVICE_REMOTE_WAKEUP, 0,    // wValue             
                        0,  // wIndex                                                             
                        0, 0, NULL, NULL);  // wLength                   
        USBTRACE2("RWU: ", rcode); 
```

**Comment by tmk** [comment]
# Power Saving

**Comment by tmk** [comment]
# Current the converter draws while in "configured"
around 22.3mA

# Current the converter draws while in "suspended"
 
## when Remote Wakeup is enabled
The converter draws around 7.8mA(without keyboard) or 8.2mA(with keyboard).

## when Remote Wakeup is disabled
The converter draws around 0.1mA.
